[features]
seeds = false
skip-lint = false
[programs.devnet]
onchain_voting = "7W9CKE2Az6zxdFryHZzMJrz89iJLd7WSWkaxx5tXn7Tx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/threedevx/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
